(cl:in-package pdu_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          GRIDADDRESS-VAL
          GRIDADDRESS
          FUSE_1-VAL
          FUSE_1
          FUSE_2-VAL
          FUSE_2
          FUSE_3-VAL
          FUSE_3
          FUSE_4-VAL
          FUSE_4
          FUSE_5-VAL
          FUSE_5
          FUSE_6-VAL
          FUSE_6
          FUSE_7-VAL
          FUSE_7
          FUSE_8-VAL
          FUSE_8
          FUSE_9-VAL
          FUSE_9
          FUSE_10-VAL
          FUSE_10
          FUSE_11-VAL
          FUSE_11
          FUSE_12-VAL
          FUSE_12
          FUSE_13-VAL
          FUSE_13
          FUSE_14-VAL
          FUSE_14
          FUSE_15-VAL
          FUSE_15
          FUSE_16-VAL
          FUSE_16
))