// Generated by gencpp from file raptor_dbw_msgs/ActuatorControlMode.msg
// DO NOT EDIT!


#ifndef RAPTOR_DBW_MSGS_MESSAGE_ACTUATORCONTROLMODE_H
#define RAPTOR_DBW_MSGS_MESSAGE_ACTUATORCONTROLMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raptor_dbw_msgs
{
template <class ContainerAllocator>
struct ActuatorControlMode_
{
  typedef ActuatorControlMode_<ContainerAllocator> Type;

  ActuatorControlMode_()
    : value(0)  {
    }
  ActuatorControlMode_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(open_loop)
  #undef open_loop
#endif
#if defined(_WIN32) && defined(closed_loop_actuator)
  #undef closed_loop_actuator
#endif
#if defined(_WIN32) && defined(closed_loop_vehicle)
  #undef closed_loop_vehicle
#endif
#if defined(_WIN32) && defined(none)
  #undef none
#endif

  enum {
    open_loop = 0u,
    closed_loop_actuator = 1u,
    closed_loop_vehicle = 2u,
    none = 255u,
  };


  typedef boost::shared_ptr< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> const> ConstPtr;

}; // struct ActuatorControlMode_

typedef ::raptor_dbw_msgs::ActuatorControlMode_<std::allocator<void> > ActuatorControlMode;

typedef boost::shared_ptr< ::raptor_dbw_msgs::ActuatorControlMode > ActuatorControlModePtr;
typedef boost::shared_ptr< ::raptor_dbw_msgs::ActuatorControlMode const> ActuatorControlModeConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator1> & lhs, const ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator1> & lhs, const ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raptor_dbw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1994ebf1d0f443ac1da4b214c3affc7f";
  }

  static const char* value(const ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1994ebf1d0f443acULL;
  static const uint64_t static_value2 = 0x1da4b214c3affc7fULL;
};

template<class ContainerAllocator>
struct DataType< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raptor_dbw_msgs/ActuatorControlMode";
  }

  static const char* value(const ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 value\n"
"\n"
"uint8 open_loop = 0\n"
"uint8 closed_loop_actuator = 1\n"
"uint8 closed_loop_vehicle = 2\n"
"uint8 none = 255\n"
;
  }

  static const char* value(const ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActuatorControlMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAPTOR_DBW_MSGS_MESSAGE_ACTUATORCONTROLMODE_H
