// Generated by gencpp from file raptor_dbw_msgs/BrakeReport.msg
// DO NOT EDIT!


#ifndef RAPTOR_DBW_MSGS_MESSAGE_BRAKEREPORT_H
#define RAPTOR_DBW_MSGS_MESSAGE_BRAKEREPORT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <raptor_dbw_msgs/ParkingBrake.h>
#include <raptor_dbw_msgs/ActuatorControlMode.h>

namespace raptor_dbw_msgs
{
template <class ContainerAllocator>
struct BrakeReport_
{
  typedef BrakeReport_<ContainerAllocator> Type;

  BrakeReport_()
    : header()
    , pedal_position(0.0)
    , pedal_output(0.0)
    , enabled(false)
    , driver_activity(false)
    , fault_brake_system(false)
    , fault_ch1(false)
    , fault_ch2(false)
    , rolling_counter(0)
    , brake_torque_actual(0.0)
    , intervention_active(false)
    , intervention_ready(false)
    , parking_brake()
    , control_type()  {
    }
  BrakeReport_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pedal_position(0.0)
    , pedal_output(0.0)
    , enabled(false)
    , driver_activity(false)
    , fault_brake_system(false)
    , fault_ch1(false)
    , fault_ch2(false)
    , rolling_counter(0)
    , brake_torque_actual(0.0)
    , intervention_active(false)
    , intervention_ready(false)
    , parking_brake(_alloc)
    , control_type(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _pedal_position_type;
  _pedal_position_type pedal_position;

   typedef float _pedal_output_type;
  _pedal_output_type pedal_output;

   typedef uint8_t _enabled_type;
  _enabled_type enabled;

   typedef uint8_t _driver_activity_type;
  _driver_activity_type driver_activity;

   typedef uint8_t _fault_brake_system_type;
  _fault_brake_system_type fault_brake_system;

   typedef uint8_t _fault_ch1_type;
  _fault_ch1_type fault_ch1;

   typedef uint8_t _fault_ch2_type;
  _fault_ch2_type fault_ch2;

   typedef uint8_t _rolling_counter_type;
  _rolling_counter_type rolling_counter;

   typedef float _brake_torque_actual_type;
  _brake_torque_actual_type brake_torque_actual;

   typedef uint8_t _intervention_active_type;
  _intervention_active_type intervention_active;

   typedef uint8_t _intervention_ready_type;
  _intervention_ready_type intervention_ready;

   typedef  ::raptor_dbw_msgs::ParkingBrake_<ContainerAllocator>  _parking_brake_type;
  _parking_brake_type parking_brake;

   typedef  ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator>  _control_type_type;
  _control_type_type control_type;





  typedef boost::shared_ptr< ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> const> ConstPtr;

}; // struct BrakeReport_

typedef ::raptor_dbw_msgs::BrakeReport_<std::allocator<void> > BrakeReport;

typedef boost::shared_ptr< ::raptor_dbw_msgs::BrakeReport > BrakeReportPtr;
typedef boost::shared_ptr< ::raptor_dbw_msgs::BrakeReport const> BrakeReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator1> & lhs, const ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pedal_position == rhs.pedal_position &&
    lhs.pedal_output == rhs.pedal_output &&
    lhs.enabled == rhs.enabled &&
    lhs.driver_activity == rhs.driver_activity &&
    lhs.fault_brake_system == rhs.fault_brake_system &&
    lhs.fault_ch1 == rhs.fault_ch1 &&
    lhs.fault_ch2 == rhs.fault_ch2 &&
    lhs.rolling_counter == rhs.rolling_counter &&
    lhs.brake_torque_actual == rhs.brake_torque_actual &&
    lhs.intervention_active == rhs.intervention_active &&
    lhs.intervention_ready == rhs.intervention_ready &&
    lhs.parking_brake == rhs.parking_brake &&
    lhs.control_type == rhs.control_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator1> & lhs, const ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raptor_dbw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd5e570d32b81ff2e399ae9770d32e16";
  }

  static const char* value(const ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd5e570d32b81ff2ULL;
  static const uint64_t static_value2 = 0xe399ae9770d32e16ULL;
};

template<class ContainerAllocator>
struct DataType< ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raptor_dbw_msgs/BrakeReport";
  }

  static const char* value(const ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# Brake pedal (%)\n"
"float32 pedal_position\n"
"float32 pedal_output\n"
"\n"
"# Status\n"
"bool enabled  # Enabled\n"
"bool driver_activity   # Driver activity\n"
"\n"
"bool fault_brake_system\n"
"\n"
"# Faults\n"
"bool fault_ch1\n"
"bool fault_ch2\n"
"\n"
"uint8 rolling_counter\n"
"\n"
"float32 brake_torque_actual # 0 to 100%\n"
"\n"
"# Anti-lock Brakes and  Stability Control\n"
"bool intervention_active\n"
"bool intervention_ready\n"
"\n"
"# Parking Brake\n"
"ParkingBrake parking_brake\n"
"\n"
"ActuatorControlMode control_type\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: raptor_dbw_msgs/ParkingBrake\n"
"uint8 status\n"
"\n"
"uint8 OFF=0\n"
"uint8 TRANS=1\n"
"uint8 ON=2\n"
"uint8 FAULT=3\n"
"\n"
"================================================================================\n"
"MSG: raptor_dbw_msgs/ActuatorControlMode\n"
"uint8 value\n"
"\n"
"uint8 open_loop = 0\n"
"uint8 closed_loop_actuator = 1\n"
"uint8 closed_loop_vehicle = 2\n"
"uint8 none = 255\n"
;
  }

  static const char* value(const ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pedal_position);
      stream.next(m.pedal_output);
      stream.next(m.enabled);
      stream.next(m.driver_activity);
      stream.next(m.fault_brake_system);
      stream.next(m.fault_ch1);
      stream.next(m.fault_ch2);
      stream.next(m.rolling_counter);
      stream.next(m.brake_torque_actual);
      stream.next(m.intervention_active);
      stream.next(m.intervention_ready);
      stream.next(m.parking_brake);
      stream.next(m.control_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BrakeReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raptor_dbw_msgs::BrakeReport_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pedal_position: ";
    Printer<float>::stream(s, indent + "  ", v.pedal_position);
    s << indent << "pedal_output: ";
    Printer<float>::stream(s, indent + "  ", v.pedal_output);
    s << indent << "enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enabled);
    s << indent << "driver_activity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.driver_activity);
    s << indent << "fault_brake_system: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fault_brake_system);
    s << indent << "fault_ch1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fault_ch1);
    s << indent << "fault_ch2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fault_ch2);
    s << indent << "rolling_counter: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rolling_counter);
    s << indent << "brake_torque_actual: ";
    Printer<float>::stream(s, indent + "  ", v.brake_torque_actual);
    s << indent << "intervention_active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.intervention_active);
    s << indent << "intervention_ready: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.intervention_ready);
    s << indent << "parking_brake: ";
    s << std::endl;
    Printer< ::raptor_dbw_msgs::ParkingBrake_<ContainerAllocator> >::stream(s, indent + "  ", v.parking_brake);
    s << indent << "control_type: ";
    s << std::endl;
    Printer< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> >::stream(s, indent + "  ", v.control_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAPTOR_DBW_MSGS_MESSAGE_BRAKEREPORT_H
