// Generated by gencpp from file raptor_dbw_msgs/HighBeamState.msg
// DO NOT EDIT!


#ifndef RAPTOR_DBW_MSGS_MESSAGE_HIGHBEAMSTATE_H
#define RAPTOR_DBW_MSGS_MESSAGE_HIGHBEAMSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raptor_dbw_msgs
{
template <class ContainerAllocator>
struct HighBeamState_
{
  typedef HighBeamState_<ContainerAllocator> Type;

  HighBeamState_()
    : value(0)  {
    }
  HighBeamState_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SNA)
  #undef SNA
#endif
#if defined(_WIN32) && defined(RESERVED)
  #undef RESERVED
#endif
#if defined(_WIN32) && defined(ON)
  #undef ON
#endif
#if defined(_WIN32) && defined(OFF)
  #undef OFF
#endif

  enum {
    SNA = 0u,
    RESERVED = 1u,
    ON = 2u,
    OFF = 0u,
  };


  typedef boost::shared_ptr< ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> const> ConstPtr;

}; // struct HighBeamState_

typedef ::raptor_dbw_msgs::HighBeamState_<std::allocator<void> > HighBeamState;

typedef boost::shared_ptr< ::raptor_dbw_msgs::HighBeamState > HighBeamStatePtr;
typedef boost::shared_ptr< ::raptor_dbw_msgs::HighBeamState const> HighBeamStateConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator1> & lhs, const ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator1> & lhs, const ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raptor_dbw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09a82263284b8122eae16e418119f715";
  }

  static const char* value(const ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09a82263284b8122ULL;
  static const uint64_t static_value2 = 0xeae16e418119f715ULL;
};

template<class ContainerAllocator>
struct DataType< ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raptor_dbw_msgs/HighBeamState";
  }

  static const char* value(const ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 value\n"
"\n"
"uint8 SNA = 0\n"
"uint8 RESERVED = 1\n"
"uint8 ON = 2\n"
"uint8 OFF = 0\n"
;
  }

  static const char* value(const ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HighBeamState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raptor_dbw_msgs::HighBeamState_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAPTOR_DBW_MSGS_MESSAGE_HIGHBEAMSTATE_H
