// Generated by gencpp from file raptor_dbw_msgs/HornState.msg
// DO NOT EDIT!


#ifndef RAPTOR_DBW_MSGS_MESSAGE_HORNSTATE_H
#define RAPTOR_DBW_MSGS_MESSAGE_HORNSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raptor_dbw_msgs
{
template <class ContainerAllocator>
struct HornState_
{
  typedef HornState_<ContainerAllocator> Type;

  HornState_()
    : status(0)  {
    }
  HornState_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(OFF)
  #undef OFF
#endif
#if defined(_WIN32) && defined(ON)
  #undef ON
#endif
#if defined(_WIN32) && defined(SNA)
  #undef SNA
#endif

  enum {
    OFF = 0u,
    ON = 1u,
    SNA = 2u,
  };


  typedef boost::shared_ptr< ::raptor_dbw_msgs::HornState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raptor_dbw_msgs::HornState_<ContainerAllocator> const> ConstPtr;

}; // struct HornState_

typedef ::raptor_dbw_msgs::HornState_<std::allocator<void> > HornState;

typedef boost::shared_ptr< ::raptor_dbw_msgs::HornState > HornStatePtr;
typedef boost::shared_ptr< ::raptor_dbw_msgs::HornState const> HornStateConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raptor_dbw_msgs::HornState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raptor_dbw_msgs::HornState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raptor_dbw_msgs::HornState_<ContainerAllocator1> & lhs, const ::raptor_dbw_msgs::HornState_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raptor_dbw_msgs::HornState_<ContainerAllocator1> & lhs, const ::raptor_dbw_msgs::HornState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raptor_dbw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::raptor_dbw_msgs::HornState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raptor_dbw_msgs::HornState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raptor_dbw_msgs::HornState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raptor_dbw_msgs::HornState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raptor_dbw_msgs::HornState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raptor_dbw_msgs::HornState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raptor_dbw_msgs::HornState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "317e8e9ee6105e8f8dcd663585539324";
  }

  static const char* value(const ::raptor_dbw_msgs::HornState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x317e8e9ee6105e8fULL;
  static const uint64_t static_value2 = 0x8dcd663585539324ULL;
};

template<class ContainerAllocator>
struct DataType< ::raptor_dbw_msgs::HornState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raptor_dbw_msgs/HornState";
  }

  static const char* value(const ::raptor_dbw_msgs::HornState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raptor_dbw_msgs::HornState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 status\n"
"\n"
"uint8 OFF = 0\n"
"uint8 ON = 1\n"
"uint8 SNA = 2\n"
;
  }

  static const char* value(const ::raptor_dbw_msgs::HornState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raptor_dbw_msgs::HornState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HornState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raptor_dbw_msgs::HornState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raptor_dbw_msgs::HornState_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAPTOR_DBW_MSGS_MESSAGE_HORNSTATE_H
