// Generated by gencpp from file raptor_dbw_msgs/LowBeam.msg
// DO NOT EDIT!


#ifndef RAPTOR_DBW_MSGS_MESSAGE_LOWBEAM_H
#define RAPTOR_DBW_MSGS_MESSAGE_LOWBEAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raptor_dbw_msgs
{
template <class ContainerAllocator>
struct LowBeam_
{
  typedef LowBeam_<ContainerAllocator> Type;

  LowBeam_()
    : status(0)  {
    }
  LowBeam_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(OFF)
  #undef OFF
#endif
#if defined(_WIN32) && defined(RESERVED)
  #undef RESERVED
#endif
#if defined(_WIN32) && defined(ON)
  #undef ON
#endif
#if defined(_WIN32) && defined(RESERVED_1)
  #undef RESERVED_1
#endif

  enum {
    OFF = 0u,
    RESERVED = 1u,
    ON = 2u,
    RESERVED_1 = 3u,
  };


  typedef boost::shared_ptr< ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> const> ConstPtr;

}; // struct LowBeam_

typedef ::raptor_dbw_msgs::LowBeam_<std::allocator<void> > LowBeam;

typedef boost::shared_ptr< ::raptor_dbw_msgs::LowBeam > LowBeamPtr;
typedef boost::shared_ptr< ::raptor_dbw_msgs::LowBeam const> LowBeamConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raptor_dbw_msgs::LowBeam_<ContainerAllocator1> & lhs, const ::raptor_dbw_msgs::LowBeam_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raptor_dbw_msgs::LowBeam_<ContainerAllocator1> & lhs, const ::raptor_dbw_msgs::LowBeam_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raptor_dbw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8826c7708bf89daa736515ad7f74a875";
  }

  static const char* value(const ::raptor_dbw_msgs::LowBeam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8826c7708bf89daaULL;
  static const uint64_t static_value2 = 0x736515ad7f74a875ULL;
};

template<class ContainerAllocator>
struct DataType< ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raptor_dbw_msgs/LowBeam";
  }

  static const char* value(const ::raptor_dbw_msgs::LowBeam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 status\n"
"\n"
"uint8 OFF = 0\n"
"uint8 RESERVED = 1\n"
"uint8 ON = 2\n"
"uint8 RESERVED_1 = 3\n"
;
  }

  static const char* value(const ::raptor_dbw_msgs::LowBeam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LowBeam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raptor_dbw_msgs::LowBeam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raptor_dbw_msgs::LowBeam_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAPTOR_DBW_MSGS_MESSAGE_LOWBEAM_H
