// Generated by gencpp from file raptor_dbw_msgs/SteeringCmd.msg
// DO NOT EDIT!


#ifndef RAPTOR_DBW_MSGS_MESSAGE_STEERINGCMD_H
#define RAPTOR_DBW_MSGS_MESSAGE_STEERINGCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <raptor_dbw_msgs/ActuatorControlMode.h>

namespace raptor_dbw_msgs
{
template <class ContainerAllocator>
struct SteeringCmd_
{
  typedef SteeringCmd_<ContainerAllocator> Type;

  SteeringCmd_()
    : angle_cmd(0.0)
    , angle_velocity(0.0)
    , enable(false)
    , ignore(false)
    , rolling_counter(0)
    , torque_cmd(0.0)
    , vehicle_curvature_cmd(0.0)
    , control_type()  {
    }
  SteeringCmd_(const ContainerAllocator& _alloc)
    : angle_cmd(0.0)
    , angle_velocity(0.0)
    , enable(false)
    , ignore(false)
    , rolling_counter(0)
    , torque_cmd(0.0)
    , vehicle_curvature_cmd(0.0)
    , control_type(_alloc)  {
  (void)_alloc;
    }



   typedef float _angle_cmd_type;
  _angle_cmd_type angle_cmd;

   typedef float _angle_velocity_type;
  _angle_velocity_type angle_velocity;

   typedef uint8_t _enable_type;
  _enable_type enable;

   typedef uint8_t _ignore_type;
  _ignore_type ignore;

   typedef uint8_t _rolling_counter_type;
  _rolling_counter_type rolling_counter;

   typedef float _torque_cmd_type;
  _torque_cmd_type torque_cmd;

   typedef float _vehicle_curvature_cmd_type;
  _vehicle_curvature_cmd_type vehicle_curvature_cmd;

   typedef  ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator>  _control_type_type;
  _control_type_type control_type;





  typedef boost::shared_ptr< ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> const> ConstPtr;

}; // struct SteeringCmd_

typedef ::raptor_dbw_msgs::SteeringCmd_<std::allocator<void> > SteeringCmd;

typedef boost::shared_ptr< ::raptor_dbw_msgs::SteeringCmd > SteeringCmdPtr;
typedef boost::shared_ptr< ::raptor_dbw_msgs::SteeringCmd const> SteeringCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator1> & lhs, const ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator2> & rhs)
{
  return lhs.angle_cmd == rhs.angle_cmd &&
    lhs.angle_velocity == rhs.angle_velocity &&
    lhs.enable == rhs.enable &&
    lhs.ignore == rhs.ignore &&
    lhs.rolling_counter == rhs.rolling_counter &&
    lhs.torque_cmd == rhs.torque_cmd &&
    lhs.vehicle_curvature_cmd == rhs.vehicle_curvature_cmd &&
    lhs.control_type == rhs.control_type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator1> & lhs, const ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raptor_dbw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "604a9bcc92c8bb45c3c9ce85f6bc45e1";
  }

  static const char* value(const ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x604a9bcc92c8bb45ULL;
  static const uint64_t static_value2 = 0xc3c9ce85f6bc45e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raptor_dbw_msgs/SteeringCmd";
  }

  static const char* value(const ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Steering Wheel\n"
"float32 angle_cmd        # degrees, range -500 to 500\n"
"float32 angle_velocity   # degrees/s, range 0 to 498, 0 = maximum\n"
"\n"
"# Enable\n"
"bool enable\n"
"\n"
"# Ignore driver overrides\n"
"bool ignore\n"
"\n"
"# Watchdog counter (optional)\n"
"uint8 rolling_counter\n"
"\n"
"float32 torque_cmd # %-torque\n"
"\n"
"float32 vehicle_curvature_cmd # 1/m\n"
"\n"
"ActuatorControlMode control_type\n"
"================================================================================\n"
"MSG: raptor_dbw_msgs/ActuatorControlMode\n"
"uint8 value\n"
"\n"
"uint8 open_loop = 0\n"
"uint8 closed_loop_actuator = 1\n"
"uint8 closed_loop_vehicle = 2\n"
"uint8 none = 255\n"
;
  }

  static const char* value(const ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle_cmd);
      stream.next(m.angle_velocity);
      stream.next(m.enable);
      stream.next(m.ignore);
      stream.next(m.rolling_counter);
      stream.next(m.torque_cmd);
      stream.next(m.vehicle_curvature_cmd);
      stream.next(m.control_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SteeringCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raptor_dbw_msgs::SteeringCmd_<ContainerAllocator>& v)
  {
    s << indent << "angle_cmd: ";
    Printer<float>::stream(s, indent + "  ", v.angle_cmd);
    s << indent << "angle_velocity: ";
    Printer<float>::stream(s, indent + "  ", v.angle_velocity);
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
    s << indent << "ignore: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ignore);
    s << indent << "rolling_counter: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rolling_counter);
    s << indent << "torque_cmd: ";
    Printer<float>::stream(s, indent + "  ", v.torque_cmd);
    s << indent << "vehicle_curvature_cmd: ";
    Printer<float>::stream(s, indent + "  ", v.vehicle_curvature_cmd);
    s << indent << "control_type: ";
    s << std::endl;
    Printer< ::raptor_dbw_msgs::ActuatorControlMode_<ContainerAllocator> >::stream(s, indent + "  ", v.control_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAPTOR_DBW_MSGS_MESSAGE_STEERINGCMD_H
