// Generated by gencpp from file raptor_dbw_msgs/WiperFront.msg
// DO NOT EDIT!


#ifndef RAPTOR_DBW_MSGS_MESSAGE_WIPERFRONT_H
#define RAPTOR_DBW_MSGS_MESSAGE_WIPERFRONT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace raptor_dbw_msgs
{
template <class ContainerAllocator>
struct WiperFront_
{
  typedef WiperFront_<ContainerAllocator> Type;

  WiperFront_()
    : status(0)  {
    }
  WiperFront_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(OFF)
  #undef OFF
#endif
#if defined(_WIN32) && defined(INTERVAL_1)
  #undef INTERVAL_1
#endif
#if defined(_WIN32) && defined(INTERVAL_2)
  #undef INTERVAL_2
#endif
#if defined(_WIN32) && defined(INTERVAL_3)
  #undef INTERVAL_3
#endif
#if defined(_WIN32) && defined(INTERVAL_4)
  #undef INTERVAL_4
#endif
#if defined(_WIN32) && defined(INTERVAL_5)
  #undef INTERVAL_5
#endif
#if defined(_WIN32) && defined(INTERVAL_6)
  #undef INTERVAL_6
#endif
#if defined(_WIN32) && defined(CONSTANT_LOW)
  #undef CONSTANT_LOW
#endif
#if defined(_WIN32) && defined(CONSTANT_HIGH)
  #undef CONSTANT_HIGH
#endif
#if defined(_WIN32) && defined(WASH_BRIEF)
  #undef WASH_BRIEF
#endif
#if defined(_WIN32) && defined(WASH_CONTINUOUS)
  #undef WASH_CONTINUOUS
#endif
#if defined(_WIN32) && defined(SNA)
  #undef SNA
#endif

  enum {
    OFF = 0u,
    INTERVAL_1 = 1u,
    INTERVAL_2 = 2u,
    INTERVAL_3 = 3u,
    INTERVAL_4 = 4u,
    INTERVAL_5 = 5u,
    INTERVAL_6 = 6u,
    CONSTANT_LOW = 11u,
    CONSTANT_HIGH = 12u,
    WASH_BRIEF = 13u,
    WASH_CONTINUOUS = 14u,
    SNA = 15u,
  };


  typedef boost::shared_ptr< ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> const> ConstPtr;

}; // struct WiperFront_

typedef ::raptor_dbw_msgs::WiperFront_<std::allocator<void> > WiperFront;

typedef boost::shared_ptr< ::raptor_dbw_msgs::WiperFront > WiperFrontPtr;
typedef boost::shared_ptr< ::raptor_dbw_msgs::WiperFront const> WiperFrontConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raptor_dbw_msgs::WiperFront_<ContainerAllocator1> & lhs, const ::raptor_dbw_msgs::WiperFront_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raptor_dbw_msgs::WiperFront_<ContainerAllocator1> & lhs, const ::raptor_dbw_msgs::WiperFront_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raptor_dbw_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f24f215ca940496a8f6a6e118de9fa5";
  }

  static const char* value(const ::raptor_dbw_msgs::WiperFront_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f24f215ca940496ULL;
  static const uint64_t static_value2 = 0xa8f6a6e118de9fa5ULL;
};

template<class ContainerAllocator>
struct DataType< ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raptor_dbw_msgs/WiperFront";
  }

  static const char* value(const ::raptor_dbw_msgs::WiperFront_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 status\n"
"\n"
"uint8 OFF = 0\n"
"uint8 INTERVAL_1 = 1\n"
"uint8 INTERVAL_2 = 2\n"
"uint8 INTERVAL_3 = 3\n"
"uint8 INTERVAL_4 = 4\n"
"uint8 INTERVAL_5 = 5\n"
"uint8 INTERVAL_6 = 6\n"
"uint8 CONSTANT_LOW = 11\n"
"uint8 CONSTANT_HIGH = 12\n"
"uint8 WASH_BRIEF = 13\n"
"uint8 WASH_CONTINUOUS = 14\n"
"uint8 SNA = 15\n"
;
  }

  static const char* value(const ::raptor_dbw_msgs::WiperFront_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WiperFront_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raptor_dbw_msgs::WiperFront_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raptor_dbw_msgs::WiperFront_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAPTOR_DBW_MSGS_MESSAGE_WIPERFRONT_H
