# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from raptor_dbw_msgs/AcceleratorPedalCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import raptor_dbw_msgs.msg

class AcceleratorPedalCmd(genpy.Message):
  _md5sum = "b4fa43636bd38fecc84a7531ea6865c4"
  _type = "raptor_dbw_msgs/AcceleratorPedalCmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Accelerator pedal (%)
float32 pedal_cmd

float32 torque_cmd # %-torque

float32 speed_cmd # m/s

# Enable
bool enable

# Ignore driver overrides
bool ignore

# Watchdog counter (optional)
uint8 rolling_counter

float32 road_slope # degrees - used with speed mode

ActuatorControlMode control_type

float32 accel_limit # m/s^2

float32 accel_positive_jerk_limit # m/s^3
================================================================================
MSG: raptor_dbw_msgs/ActuatorControlMode
uint8 value

uint8 open_loop = 0
uint8 closed_loop_actuator = 1
uint8 closed_loop_vehicle = 2
uint8 none = 255"""
  __slots__ = ['pedal_cmd','torque_cmd','speed_cmd','enable','ignore','rolling_counter','road_slope','control_type','accel_limit','accel_positive_jerk_limit']
  _slot_types = ['float32','float32','float32','bool','bool','uint8','float32','raptor_dbw_msgs/ActuatorControlMode','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pedal_cmd,torque_cmd,speed_cmd,enable,ignore,rolling_counter,road_slope,control_type,accel_limit,accel_positive_jerk_limit

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AcceleratorPedalCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pedal_cmd is None:
        self.pedal_cmd = 0.
      if self.torque_cmd is None:
        self.torque_cmd = 0.
      if self.speed_cmd is None:
        self.speed_cmd = 0.
      if self.enable is None:
        self.enable = False
      if self.ignore is None:
        self.ignore = False
      if self.rolling_counter is None:
        self.rolling_counter = 0
      if self.road_slope is None:
        self.road_slope = 0.
      if self.control_type is None:
        self.control_type = raptor_dbw_msgs.msg.ActuatorControlMode()
      if self.accel_limit is None:
        self.accel_limit = 0.
      if self.accel_positive_jerk_limit is None:
        self.accel_positive_jerk_limit = 0.
    else:
      self.pedal_cmd = 0.
      self.torque_cmd = 0.
      self.speed_cmd = 0.
      self.enable = False
      self.ignore = False
      self.rolling_counter = 0
      self.road_slope = 0.
      self.control_type = raptor_dbw_msgs.msg.ActuatorControlMode()
      self.accel_limit = 0.
      self.accel_positive_jerk_limit = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3f3BfB2f().pack(_x.pedal_cmd, _x.torque_cmd, _x.speed_cmd, _x.enable, _x.ignore, _x.rolling_counter, _x.road_slope, _x.control_type.value, _x.accel_limit, _x.accel_positive_jerk_limit))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.control_type is None:
        self.control_type = raptor_dbw_msgs.msg.ActuatorControlMode()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.pedal_cmd, _x.torque_cmd, _x.speed_cmd, _x.enable, _x.ignore, _x.rolling_counter, _x.road_slope, _x.control_type.value, _x.accel_limit, _x.accel_positive_jerk_limit,) = _get_struct_3f3BfB2f().unpack(str[start:end])
      self.enable = bool(self.enable)
      self.ignore = bool(self.ignore)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3f3BfB2f().pack(_x.pedal_cmd, _x.torque_cmd, _x.speed_cmd, _x.enable, _x.ignore, _x.rolling_counter, _x.road_slope, _x.control_type.value, _x.accel_limit, _x.accel_positive_jerk_limit))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.control_type is None:
        self.control_type = raptor_dbw_msgs.msg.ActuatorControlMode()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.pedal_cmd, _x.torque_cmd, _x.speed_cmd, _x.enable, _x.ignore, _x.rolling_counter, _x.road_slope, _x.control_type.value, _x.accel_limit, _x.accel_positive_jerk_limit,) = _get_struct_3f3BfB2f().unpack(str[start:end])
      self.enable = bool(self.enable)
      self.ignore = bool(self.ignore)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f3BfB2f = None
def _get_struct_3f3BfB2f():
    global _struct_3f3BfB2f
    if _struct_3f3BfB2f is None:
        _struct_3f3BfB2f = struct.Struct("<3f3BfB2f")
    return _struct_3f3BfB2f
