# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from raptor_dbw_msgs/SurroundReport.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import raptor_dbw_msgs.msg
import std_msgs.msg

class SurroundReport(genpy.Message):
  _md5sum = "7fb6baa192c10e400b9071053bd9c683"
  _type = "raptor_dbw_msgs/SurroundReport"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

float32 front_radar_object_distance # meters
float32 rear_radar_object_distance # meters

SonarArcNum rear_right
SonarArcNum rear_left
SonarArcNum rear_center
SonarArcNum front_right
SonarArcNum front_left
SonarArcNum front_center

bool front_radar_distance_valid
bool parking_sonar_data_valid

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: raptor_dbw_msgs/SonarArcNum
uint8 status

# Unitless - based on bars on display
uint8 NO_DISTANCE = 0
uint8 ARC1 = 1
uint8 ARC2 = 2
uint8 ARC3 = 3
uint8 ARC4 = 4
uint8 ARC5 = 5
uint8 ARC6 = 6
uint8 ARC7 = 7
uint8 ARC8 = 8
uint8 NO_ARC = 15
"""
  __slots__ = ['header','front_radar_object_distance','rear_radar_object_distance','rear_right','rear_left','rear_center','front_right','front_left','front_center','front_radar_distance_valid','parking_sonar_data_valid']
  _slot_types = ['std_msgs/Header','float32','float32','raptor_dbw_msgs/SonarArcNum','raptor_dbw_msgs/SonarArcNum','raptor_dbw_msgs/SonarArcNum','raptor_dbw_msgs/SonarArcNum','raptor_dbw_msgs/SonarArcNum','raptor_dbw_msgs/SonarArcNum','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,front_radar_object_distance,rear_radar_object_distance,rear_right,rear_left,rear_center,front_right,front_left,front_center,front_radar_distance_valid,parking_sonar_data_valid

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SurroundReport, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.front_radar_object_distance is None:
        self.front_radar_object_distance = 0.
      if self.rear_radar_object_distance is None:
        self.rear_radar_object_distance = 0.
      if self.rear_right is None:
        self.rear_right = raptor_dbw_msgs.msg.SonarArcNum()
      if self.rear_left is None:
        self.rear_left = raptor_dbw_msgs.msg.SonarArcNum()
      if self.rear_center is None:
        self.rear_center = raptor_dbw_msgs.msg.SonarArcNum()
      if self.front_right is None:
        self.front_right = raptor_dbw_msgs.msg.SonarArcNum()
      if self.front_left is None:
        self.front_left = raptor_dbw_msgs.msg.SonarArcNum()
      if self.front_center is None:
        self.front_center = raptor_dbw_msgs.msg.SonarArcNum()
      if self.front_radar_distance_valid is None:
        self.front_radar_distance_valid = False
      if self.parking_sonar_data_valid is None:
        self.parking_sonar_data_valid = False
    else:
      self.header = std_msgs.msg.Header()
      self.front_radar_object_distance = 0.
      self.rear_radar_object_distance = 0.
      self.rear_right = raptor_dbw_msgs.msg.SonarArcNum()
      self.rear_left = raptor_dbw_msgs.msg.SonarArcNum()
      self.rear_center = raptor_dbw_msgs.msg.SonarArcNum()
      self.front_right = raptor_dbw_msgs.msg.SonarArcNum()
      self.front_left = raptor_dbw_msgs.msg.SonarArcNum()
      self.front_center = raptor_dbw_msgs.msg.SonarArcNum()
      self.front_radar_distance_valid = False
      self.parking_sonar_data_valid = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2f8B().pack(_x.front_radar_object_distance, _x.rear_radar_object_distance, _x.rear_right.status, _x.rear_left.status, _x.rear_center.status, _x.front_right.status, _x.front_left.status, _x.front_center.status, _x.front_radar_distance_valid, _x.parking_sonar_data_valid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.rear_right is None:
        self.rear_right = raptor_dbw_msgs.msg.SonarArcNum()
      if self.rear_left is None:
        self.rear_left = raptor_dbw_msgs.msg.SonarArcNum()
      if self.rear_center is None:
        self.rear_center = raptor_dbw_msgs.msg.SonarArcNum()
      if self.front_right is None:
        self.front_right = raptor_dbw_msgs.msg.SonarArcNum()
      if self.front_left is None:
        self.front_left = raptor_dbw_msgs.msg.SonarArcNum()
      if self.front_center is None:
        self.front_center = raptor_dbw_msgs.msg.SonarArcNum()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.front_radar_object_distance, _x.rear_radar_object_distance, _x.rear_right.status, _x.rear_left.status, _x.rear_center.status, _x.front_right.status, _x.front_left.status, _x.front_center.status, _x.front_radar_distance_valid, _x.parking_sonar_data_valid,) = _get_struct_2f8B().unpack(str[start:end])
      self.front_radar_distance_valid = bool(self.front_radar_distance_valid)
      self.parking_sonar_data_valid = bool(self.parking_sonar_data_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2f8B().pack(_x.front_radar_object_distance, _x.rear_radar_object_distance, _x.rear_right.status, _x.rear_left.status, _x.rear_center.status, _x.front_right.status, _x.front_left.status, _x.front_center.status, _x.front_radar_distance_valid, _x.parking_sonar_data_valid))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.rear_right is None:
        self.rear_right = raptor_dbw_msgs.msg.SonarArcNum()
      if self.rear_left is None:
        self.rear_left = raptor_dbw_msgs.msg.SonarArcNum()
      if self.rear_center is None:
        self.rear_center = raptor_dbw_msgs.msg.SonarArcNum()
      if self.front_right is None:
        self.front_right = raptor_dbw_msgs.msg.SonarArcNum()
      if self.front_left is None:
        self.front_left = raptor_dbw_msgs.msg.SonarArcNum()
      if self.front_center is None:
        self.front_center = raptor_dbw_msgs.msg.SonarArcNum()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.front_radar_object_distance, _x.rear_radar_object_distance, _x.rear_right.status, _x.rear_left.status, _x.rear_center.status, _x.front_right.status, _x.front_left.status, _x.front_center.status, _x.front_radar_distance_valid, _x.parking_sonar_data_valid,) = _get_struct_2f8B().unpack(str[start:end])
      self.front_radar_distance_valid = bool(self.front_radar_distance_valid)
      self.parking_sonar_data_valid = bool(self.parking_sonar_data_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f8B = None
def _get_struct_2f8B():
    global _struct_2f8B
    if _struct_2f8B is None:
        _struct_2f8B = struct.Struct("<2f8B")
    return _struct_2f8B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
