(cl:in-package raptor_dbw_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TURN_SIGNAL_STATE-VAL
          TURN_SIGNAL_STATE
          RIGHT_REAR_DOOR_STATE-VAL
          RIGHT_REAR_DOOR_STATE
          HIGH_BEAM_STATE-VAL
          HIGH_BEAM_STATE
          FRONT_WIPER_STATE-VAL
          FRONT_WIPER_STATE
          REAR_WIPER_STATE-VAL
          REAR_WIPER_STATE
          IGNITION_STATE-VAL
          IGNITION_STATE
          LEFT_REAR_DOOR_STATE-VAL
          LEFT_REAR_DOOR_STATE
          LIFTGATE_DOOR_STATE-VAL
          LIFTGATE_DOOR_STATE
          HORN_STATE-VAL
          HORN_STATE
          LOW_BEAM_STATE-VAL
          LOW_BEAM_STATE
          ROLLING_COUNTER-VAL
          ROLLING_COUNTER
))