(cl:in-package raptor_dbw_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          AUTONOMOUS_DISABLED_NO_BRAKES-VAL
          AUTONOMOUS_DISABLED_NO_BRAKES
          AUTONOMOUS_DISABLED_APPLY_BRAKES-VAL
          AUTONOMOUS_DISABLED_APPLY_BRAKES
          CAN_GATEWAY_DISABLED-VAL
          CAN_GATEWAY_DISABLED
          INVERTER_CONTACTOR_DISABLED-VAL
          INVERTER_CONTACTOR_DISABLED
          PREVENT_ENTER_AUTONOMOUS_MODE-VAL
          PREVENT_ENTER_AUTONOMOUS_MODE
          WARN_DRIVER_ONLY-VAL
          WARN_DRIVER_ONLY
))