(cl:in-package raptor_dbw_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          PEDAL_POSITION-VAL
          PEDAL_POSITION
          PEDAL_OUTPUT-VAL
          PEDAL_OUTPUT
          ENABLED-VAL
          ENABLED
          DRIVER_ACTIVITY-VAL
          DRIVER_ACTIVITY
          FAULT_BRAKE_SYSTEM-VAL
          FAULT_BRAKE_SYSTEM
          FAULT_CH1-VAL
          FAULT_CH1
          FAULT_CH2-VAL
          FAULT_CH2
          ROLLING_COUNTER-VAL
          ROLLING_COUNTER
          BRAKE_TORQUE_ACTUAL-VAL
          BRAKE_TORQUE_ACTUAL
          INTERVENTION_ACTIVE-VAL
          INTERVENTION_ACTIVE
          INTERVENTION_READY-VAL
          INTERVENTION_READY
          PARKING_BRAKE-VAL
          PARKING_BRAKE
          CONTROL_TYPE-VAL
          CONTROL_TYPE
))