(cl:in-package raptor_dbw_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          FRONT_RADAR_OBJECT_DISTANCE-VAL
          FRONT_RADAR_OBJECT_DISTANCE
          REAR_RADAR_OBJECT_DISTANCE-VAL
          REAR_RADAR_OBJECT_DISTANCE
          REAR_RIGHT-VAL
          REAR_RIGHT
          REAR_LEFT-VAL
          REAR_LEFT
          REAR_CENTER-VAL
          REAR_CENTER
          FRONT_RIGHT-VAL
          FRONT_RIGHT
          FRONT_LEFT-VAL
          FRONT_LEFT
          FRONT_CENTER-VAL
          FRONT_CENTER
          FRONT_RADAR_DISTANCE_VALID-VAL
          FRONT_RADAR_DISTANCE_VALID
          PARKING_SONAR_DATA_VALID-VAL
          PARKING_SONAR_DATA_VALID
))