(cl:in-package raptor_dbw_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          STEERING_WHEEL_ANGLE-VAL
          STEERING_WHEEL_ANGLE
          STEERING_WHEEL_ANGLE_CMD-VAL
          STEERING_WHEEL_ANGLE_CMD
          STEERING_WHEEL_TORQUE-VAL
          STEERING_WHEEL_TORQUE
          ENABLED-VAL
          ENABLED
          DRIVER_ACTIVITY-VAL
          DRIVER_ACTIVITY
          FAULT_STEERING_SYSTEM-VAL
          FAULT_STEERING_SYSTEM
          OVERHEAT_PREVENTION_MODE-VAL
          OVERHEAT_PREVENTION_MODE
          ROLLING_COUNTER-VAL
          ROLLING_COUNTER
          CONTROL_TYPE-VAL
          CONTROL_TYPE
          STEERING_OVERHEAT_WARNING-VAL
          STEERING_OVERHEAT_WARNING
))