// Generated by gencpp from file deeporange14_msgs/MissionStatus.msg
// DO NOT EDIT!


#ifndef DEEPORANGE14_MSGS_MESSAGE_MISSIONSTATUS_H
#define DEEPORANGE14_MSGS_MESSAGE_MISSIONSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace deeporange14_msgs
{
template <class ContainerAllocator>
struct MissionStatus_
{
  typedef MissionStatus_<ContainerAllocator> Type;

  MissionStatus_()
    : header()
    , status()
    , stop_ros(false)  {
    }
  MissionStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(_alloc)
    , stop_ros(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;

   typedef uint8_t _stop_ros_type;
  _stop_ros_type stop_ros;





  typedef boost::shared_ptr< ::deeporange14_msgs::MissionStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deeporange14_msgs::MissionStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MissionStatus_

typedef ::deeporange14_msgs::MissionStatus_<std::allocator<void> > MissionStatus;

typedef boost::shared_ptr< ::deeporange14_msgs::MissionStatus > MissionStatusPtr;
typedef boost::shared_ptr< ::deeporange14_msgs::MissionStatus const> MissionStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deeporange14_msgs::MissionStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deeporange14_msgs::MissionStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::deeporange14_msgs::MissionStatus_<ContainerAllocator1> & lhs, const ::deeporange14_msgs::MissionStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.status == rhs.status &&
    lhs.stop_ros == rhs.stop_ros;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::deeporange14_msgs::MissionStatus_<ContainerAllocator1> & lhs, const ::deeporange14_msgs::MissionStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace deeporange14_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::deeporange14_msgs::MissionStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deeporange14_msgs::MissionStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deeporange14_msgs::MissionStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deeporange14_msgs::MissionStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deeporange14_msgs::MissionStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deeporange14_msgs::MissionStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deeporange14_msgs::MissionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edb2d94e8a16ca298be038805a2c00e1";
  }

  static const char* value(const ::deeporange14_msgs::MissionStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xedb2d94e8a16ca29ULL;
  static const uint64_t static_value2 = 0x8be038805a2c00e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::deeporange14_msgs::MissionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deeporange14_msgs/MissionStatus";
  }

  static const char* value(const ::deeporange14_msgs::MissionStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deeporange14_msgs::MissionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"string status\n"
"bool stop_ros\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::deeporange14_msgs::MissionStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deeporange14_msgs::MissionStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
      stream.next(m.stop_ros);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deeporange14_msgs::MissionStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deeporange14_msgs::MissionStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
    s << indent << "stop_ros: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop_ros);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPORANGE14_MSGS_MESSAGE_MISSIONSTATUS_H
