// Generated by gencpp from file pdu_msgs/RelayState.msg
// DO NOT EDIT!


#ifndef PDU_MSGS_MESSAGE_RELAYSTATE_H
#define PDU_MSGS_MESSAGE_RELAYSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pdu_msgs
{
template <class ContainerAllocator>
struct RelayState_
{
  typedef RelayState_<ContainerAllocator> Type;

  RelayState_()
    : value(0)  {
    }
  RelayState_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(RELAY_OFF)
  #undef RELAY_OFF
#endif
#if defined(_WIN32) && defined(RELAY_ON)
  #undef RELAY_ON
#endif
#if defined(_WIN32) && defined(MAINTAIN_STATE)
  #undef MAINTAIN_STATE
#endif

  enum {
    RELAY_OFF = 0u,
    RELAY_ON = 1u,
    MAINTAIN_STATE = 2u,
  };


  typedef boost::shared_ptr< ::pdu_msgs::RelayState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pdu_msgs::RelayState_<ContainerAllocator> const> ConstPtr;

}; // struct RelayState_

typedef ::pdu_msgs::RelayState_<std::allocator<void> > RelayState;

typedef boost::shared_ptr< ::pdu_msgs::RelayState > RelayStatePtr;
typedef boost::shared_ptr< ::pdu_msgs::RelayState const> RelayStateConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pdu_msgs::RelayState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pdu_msgs::RelayState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pdu_msgs::RelayState_<ContainerAllocator1> & lhs, const ::pdu_msgs::RelayState_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pdu_msgs::RelayState_<ContainerAllocator1> & lhs, const ::pdu_msgs::RelayState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pdu_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pdu_msgs::RelayState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pdu_msgs::RelayState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pdu_msgs::RelayState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pdu_msgs::RelayState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pdu_msgs::RelayState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pdu_msgs::RelayState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pdu_msgs::RelayState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fde2a8d5834550d49c7175d413bd2df";
  }

  static const char* value(const ::pdu_msgs::RelayState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fde2a8d5834550dULL;
  static const uint64_t static_value2 = 0x49c7175d413bd2dfULL;
};

template<class ContainerAllocator>
struct DataType< ::pdu_msgs::RelayState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pdu_msgs/RelayState";
  }

  static const char* value(const ::pdu_msgs::RelayState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pdu_msgs::RelayState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 value\n"
"\n"
"# MAINTAIN_STATE items perform the same function.\n"
"uint8 RELAY_OFF = 0\n"
"uint8 RELAY_ON = 1\n"
"uint8 MAINTAIN_STATE = 2\n"
;
  }

  static const char* value(const ::pdu_msgs::RelayState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pdu_msgs::RelayState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelayState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pdu_msgs::RelayState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pdu_msgs::RelayState_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PDU_MSGS_MESSAGE_RELAYSTATE_H
